#!/usr/bin/perl
 
use strict;
use warnings;

my $version = "1.1" ; 
my $host   = "R-int";
my $domain = "gsb.lan";

my $eth0ip     = "172.16.0.254";
my $mask   = "255.255.255.0";
my $eth1ip     = "192.168.200.254";
my $gw     = "192.168.200.253";
my $eth2ip     = "172.16.64.254";
my $eth3ip     = "172.16.65.254";
my $dns1   = "172.16.0.1";
my $dns2   = "172.16.0.6";
# les paquets a installer 
my $packages = "postfix isc-dhcp-server";
 
sub putconf {
        my ($file, $msg)= @_;
        print "Generation du fichier $file ...\n";
        my $dat = `date`;
        open (FILE, ">$file") or die "Erreur ecriture fichier $file : $! \n";
        print FILE "### $version - putconf - $dat" if ($file ne "/etc/hostname") ;
        print FILE $msg;
        close FILE;
};

 
system "aptitude install -y $packages" if ($packages);

putconf("/etc/hostname", "$host\n");
 
putconf ("/etc/hosts",
"127.0.0.1      localhost.localdomain localhost
127.0.1.1       $host
$eth0ip     $host.$domain $host
$eth1ip     $host.$domain $host
$eth2ip     $host.$domain $host
$eth3ip     $host.$domain $host
 
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
");
 
putconf ("/etc/network/interfaces",
"
# The loopback network interface
auto lo
iface lo inet loopback
 
# The primary network interface
allow-hotplug eth0
iface eth0 inet static
        address $eth0ip
        netmask $mask

allow-hotplug eth1
iface eth1 inet static
        address $eth1ip
        netmask $mask
        gateway $gw
	post-up  /etc/network/if-up.d/routage

allow-hotplug eth2
iface eth2 inet static
        address $eth2ip
        netmask $mask

allow-hotplug eth3
iface eth3 inet static
        address $eth3ip
        netmask $mask

iface eth4 inet dhcp
");
 
putconf ("/etc/network/if-up.d/routage",
"#!/bin/bash
echo 1 > /proc/sys/net/ipv4/ip_forward
");
system "chmod +x /etc/network/if-up.d/routage";

putconf ("/etc/resolv.conf",
"domain $domain
nameserver $dns1
nameserver $dns2
");
 

putconf ("/etc/dhcp/dhcpd.conf",
"ddns-update-style none;

option domain-name \"$domain\";
option domain-name-servers $dns1, $dns2;

default-lease-time 600;
max-lease-time 7200;

log-facility local7;
#user
subnet 172.16.64.0 netmask 255.255.255.0 {
  range 172.16.64.20 172.16.64.120;
  option domain-name-servers $dns1, $dns2;
  option domain-name \"$domain\";
  option routers 172.16.64.254;
  option broadcast-address 172.16.64.255;
  default-lease-time 86400;
  max-lease-time 604800;
}

#wifi
subnet 172.16.65.0 netmask 255.255.255.0 {
  range 172.16.65.20 172.16.65.70;
  option domain-name-servers $dns1, $dns2;
  option domain-name \"$domain\";
  option routers 172.16.65.254;
  option broadcast-address 172.16.65.255;
  default-lease-time 600;
  max-lease-time 7200;
}
");
system "echo '*.* \@S-infra' >> /etc/rsyslog.conf " ;

system("service isc-dhcp-server restart");